config/routes.rb
RailsStore::Application.routes.draw do
  resources :reviews, :only => [ :new, :create, :edit, :show, :update]

  resources :products

  post '/products/:id' => 'products#add_to_cart', :as => 'add_product' 
  post '/products/:id' => 'products#remove_from_cart', :as => 'remove_product'

  

    root :to => 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :description, :image_url, :in_cart

  has_many :reviews
  validates :name, :uniqueness => true
  validates :name, :price, :presence => true


end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :body, :product_id, :rating
  validates :body, :length => { :in => 50..1000}
  validates :rating, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 5 }

  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json


  before_filter :products_in_cart

  def products_in_cart
    @products_in_cart = Product.where(:in_cart => true )
    @prices_in_cart = @products_in_cart.map{|product| product.price } #array output
    @total_price = @prices_in_cart.reduce(:+)
  end


  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id]) 
    # @product_id = @product.id
    # @review = Review.find(@product_id)

    # @reviews = Review.where(:product_id => params[:id])
    @reviews = Review.where(:product_id => @product.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    #@product = Product.find(params[:product_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  def add_to_cart
    # @product = Product.find(params[:id])

    id = params[:id]
    @product = Product.find id
    # @product.in_cart = true
    @product[:in_cart] = 't'
    
    # @product.update_attributes({:in_cart => true})
    respond_to do |format|
      @product.update_attributes(params[:product])
      format.html { redirect_to products_url, notice: 'Product was successfully added to cart.' }
      format.json { head :no_content }
    end
  end

  def remove_from_cart
    @product = Product.find(params[:id])
    @product[:in_cart] = 'f'
    @product.save
    
    # @product.update_attributes({:in_cart => true})
    respond_to do |format|
      @product.update_attributes(params[:product])
      format.html { redirect_to products_url, notice: 'Product was successfully added to cart.' }
      format.json { head :no_content }
    end
  end
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  # def index
  #   @reviews = Review.all

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @reviews }
  #   end
  # end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new
    # if params[:product_id] != nil
      @product = Product.find(params[:product_id]) if params[:product_id]
    # end

      @products = Product.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @product = Product.find(params[:product_id]) if params[:product_id]

    @products = Product.all
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  # def destroy
  #   @review = Review.find(params[:id])
  #   @review.destroy

  #   respond_to do |format|
  #     format.html { redirect_to reviews_url }
  #     format.json { head :no_content }
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <body id="home">
    <div id="outer-container">
      <div id="inner-container">
        <h1><%= link_to 'Mobility Store', '/' %></h1>
        <div class="container-fluid">
          <div class="row-fluid">
            <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <%= render 'cart' %>
            </div>
          </div>
        </div>

      
      </div>
    </div>
</body>
</html>

app/views/products/_addcart.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      
      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div>
  <% if @product.in_cart == false %>
     <%= f.hidden_field :in_cart, :value => true %>
     <%= f.submit "Add to Cart" %>
  <% else %>
     <%= f.hidden_field :in_cart, :value => false %>
     <%= f.submit "Remove from Cart" %>
  <% end %>
  </div>
<% end %>

app/views/products/_addtocart.html.erb
# <%= form_for(@product) do |f| %>

#   <div class="field">
#     <%= f.label :in_cart %><br />
#     <%= f.check_box :in_cart %>
#   </div>
#   <div class="actions">
#     <%= f.submit %>
#   </div>
# <% end %>


<form action="/products/<%= @product.id %>/addtocart" method="post">


  <div class="actions">
    <input name="commit" type="submit" value="Add Product" />
  </div>


</form>

app/views/products/_cart.html.erb
<div class="cart">
<h2>My Cart</h2>
<table>
<% @products_in_cart.each do |product| %>
<tr>
 <td><%= product.name %> </td>
 <td class="price"><%= number_to_currency(product.price) %> </td>
</tr>
 <% end %>
<tr>
 <td>&#32;</td>
 <td>&#32;</td>
  <td>&#32;</td>
   <td>&#32;</td>
    <td>&#32;</td>
</tr> 
<tr>
 <td>Total price: </td>
 <td><%= number_to_currency(@total_price) %> </td>
</tr> 
 </table>	
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      
      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :in_cart %><br />
    <%= f.check_box :in_cart %>
  </div>







  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p><%= link_to 'New Product', new_product_path %>

</p>
<table>
<% @products.each do |product| %>
  <div class='listings'>
    <p><%= link_to image_tag( product.image_url ), product %></p>

    <p class="productname"><%= product.name %></p>
    
    <p class="split-para"><%= number_to_currency(product.price) %>
    <% if product.in_cart == true %>
    <span>In Cart</span></p>
    <% else %>
    <span class="btn btn-mini btn-success" type="button"><%= link_to 'Add to Cart', product, method: :post %></span></p>
    <% end %>

    <!-- <p><%= link_to 'Edit', edit_product_path(product) %></p>
    <p><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure you want to remove the product?' } %></p>
 -->  </div>
<% end %>
</table>



<br />

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <div class="span6">
        <div class="showimage">
          <img src="<%= @product.image_url %>" />
        </div>

      </div>
      <div class="span6 pagefunctions">
      <p class="showpageprice">
        <%= number_to_currency(@product.price) %>
      </p>    
      <p><%= render 'addcart' %></p>
      
      <% if @reviews.count == 1 %>
      <p><%= @reviews.count %> review</p>
      <% else %>
      <p><%= @reviews.count %> reviews</p>

      <% end %>

      <p class="btn btn-success"><%= link_to 'Edit Product', edit_product_path(@product) %></p>

      </div>
    </div>
  </div>
</div>



<p class="showpagename">
  <%= @product.name %>
</p>

<p class="showpagedescription">
  <b>Description:</b>
  <%= @product.description %>
</p>

<p class="showpagereviews">
Reviews:
<p>
<% @reviews.each do |review| %>
  <p class="showpagestars"><%  review.rating.round.times do %><img src="http://cdn1.iconfinder.com/data/icons/diagona/icon/16/031.png" />
<% end %></p>
  <p class="showpageonereview"><%= review.body %>
<% end %>
</p>
<p class="showpageaddreview btn btn-success"><a href="/reviews/new?product_id=<%= @product.id %>">Add Review</a>
</p>

<!-- <p>
  <b>In Cart:</b>
  <%= @product.in_cart %>
</p> -->

<!-- <p><%= render 'addcart' %></p> |
<%= link_to 'Back', products_path %>
 -->

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">

    <% if @product %>
      <input type="hidden" name='review[product_id]' value='<%= @product.id %>'/>
    <% else %>
      <%= f.label :product_id %><br />
      
      <select name='review[product_id]'>
        <% @products.each do |product| %>
          <option value='<%= product.id %>'>
            <%= product.name %>
          </option>
        <% end %>
      </select>     

  
    <% end %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back to Products', products_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Rating</th>
    <th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.body %></td>
    <td><%= review.rating %></td>
    <td><%= review.product_id %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back to Products', products_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @review.body %>
</p>

<p>
  <b>Rating:</b>
  <%= @review.rating %>
</p>

<p>
  <b>Product:</b>
  <%= @review.product_id %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back to Products', products_path %>